### PR TITLE
Artifactory documentation for DC/OS v1.10

### PR DESCRIPTION
**Pull request by sgerrand**
💁 Resolves https://jira.mesosphere.com/browse/DCOS_COMMUNITY-105

### CODE REVIEW

**Comment by sgerrand** [comment]
👋 @ryadav88: Would you please review this change.

**Comment by pleia2** [comment]
Thank you for your work on this, I made my way for through the Pro instructions, and so far so good, but did you test out the instructions in using-artifactory.md for using Artifactory on DC/OS as a Docker Registry (this is linked at the bottom of artifactory-lb.md)? It looks like the screenshots weren't updated for 1.9 either, so it has some pretty old content in there.

**Comment by sgerrand** [comment]
An astute observation. I neglected to update them. I'll do so this weekend.

**Comment by pleia2** [comment]
@sgerrand Were you able to have a look at this? It's OK if you don't have time for it, we can merge this as-is and do a follow-up PR with the rest of the update.

Thanks for your work!

**Comment by pleia2** [comment]
Making a note to do a follow-up PR. As noted, it wasn't updated for 1.9 either.

**Pull request merged**
