### PR TITLE
Remove reference to VIPs

### PR DESCRIPTION
**Pull request by shashiranjan84**
Docs updated to sync with https://github.com/mesosphere/universe/pull/1225

### CODE REVIEW

**Comment by OhRobin** [comment]
Installing with Cassandra was not a problem, but installing with Postgresql ran into the following issue: 


`I0620 01:01:12.418658 10692 exec.cpp:162] Version: 1.2.1 I0620 01:01:12.428738 10710 exec.cpp:237] Executor registered on agent 75b86094-d856-4ec7-80d9-5bf60176905f-S2 Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] host not found`

**Comment by shashiranjan84** [comment]
thanks @OhRobin, would you please share the provisioned kong config file?

**Comment by shashiranjan84** [comment]
@OhRobin I did notice that in example I created `Posgresql` app with name `postgres` but I used `postgresql.marathon.l4lb.thisdcos.directory:5432` in Kong config, which is wrong. I have fixed it in the PR.

But the error you getting is because `postgres.host` not being set. If you provide me Kong config you used to provision it, it would help me to debug the issue further.

**Comment by shashiranjan84** [comment]
I tested with following configuration:

Postgresql

```bash
{
  "service": {
    "name": "postgresql"
  },
  "postgresql": {
    "cpus": 0.3,
    "mem": 512
  },
  "database": {
    "username": "kong",
    "password": "kong",
    "dbname": "kong"
  },
  "storage": {
    "host_volume": "/tmp",
    "pgdata": "pgdata",
    "persistence": {
      "enable": true,
      "volume_size": 512,
      "external": {
        "enable": false,
        "volume_name": "postgresql",
        "provider": "dvdi",
        "driver": "rexray"
      }
    }
  },
  "networking": {
    "port": 5432,
    "host_mode": false,
    "external_access": {
      "enable": false,
      "external_access_port": 15432
    }
  }
}
```

Kong

```bash
{
  "service": {
    "name": "kong"
  },
  "configurations": {
    "postgres": {
      "host": "postgresql.marathon.l4lb.thisdcos.directory",
      "port": 5432,
      "database": "kong",
      "user": "kong",
      "password": "kong"
    },
    "cassandra": {
      "use-cassandra": false,
      "contact-points": "node-0.cassandra.mesos, node-1.cassandra.mesos, node-2.cassandra.mesos",
      "port": 9042,
      "keyspace": "kong"
    }
  },
  "networking": {
    "proxy": {
      "external-access": true,
      "virtual-host": "mesos-tes-PublicSl-1TJB5U5K35XXT-591175086.us-east-1.elb.amazonaws.com",
      "https-redirect": false,
      "service-port": 10201
    },
    "admin": {
      "external-access": true,
      "https-redirect": false,
      "service-port": 10202
    }
  }
}
```

**Comment by OhRobin** [comment]
I used 
`{
  "service": {
    "name": "kong"
  },
  "configurations": {
    "postgres": {
      "host": "postgresql.marathon.l4lb.thisdcos.directory:5432",
      "port": 5432,
      "database": "kong",
      "user": "kong",
      "password": "kong"
    },
    "cassandra": {
      "use-cassandra": false,
      "contact-points": "node-0.cassandra.mesos, node-1.cassandra.mesos, node-2.cassandra.mesos",
      "port": 9042,
      "keyspace": "kong"
    }
  },
  "networking": {
    "proxy": {
      "external-access": true,
      "virtual-host": "mesos-tes-PublicSl-1TJB5U5K35XXT-591175086.us-east-1.elb.amazonaws.com",
      "https-redirect": false,
      "service-port": 10201
    },
    "admin": {
      "external-access": true,
      "https-redirect": false,
      "service-port": 10202
    }
  }
}

`

I can try again with the updated version

**Comment by shashiranjan84** [comment]
@OhRobin were you trying to `add` new instance or update existing Kong app new properties? I doubt update will work.

**Comment by shashiranjan84** [comment]
@OhRobin were you able to retest?

**Comment by OhRobin** [comment]
@shashiranjan84 retested. it is working

**Pull request merged**
