### PR TITLE
Portworx Examples

### PR DESCRIPTION
**Pull request by jsilberm**
Documentation Examples to correspond with PR 
https://github.com/mesosphere/universe/pull/883

### CODE REVIEW

**Comment by mhausenblas** [comment]
Any updates here @jsilberm @ryadav88 ?

**Comment by jsilberm** [comment]
I responded to all of the review points that @ryadav88 raised.   The 'universe' PR should be ready to go.   If not, please let me know what to address.  Thanks.

**Comment by mhausenblas** [comment]
Awesome, thanks for the confirmation @jsilberm! @ryadav88?

**Comment by mhausenblas** [comment]
Thank you!

**Pull request merged**
