### PR TITLE
Scale 5.0.0 dropping DCOS 1.8. Added workspace clarification.

### PR DESCRIPTION
**Pull request by gisjedi**
With the upcoming Scale 5.0.0 release we will be dropping support for DCOS 1.8 and requiring DCOS 1.9 as the minimum version. This PR can be held off until the Scale 5.0.0 PR is made against the DCOS Universe.

Also added some clarification of Scale Workspace usage in documentation.

### CODE REVIEW

**Comment by gisjedi** [comment]
This is ready to go as the release has been made and universe PR submitted. https://github.com/mesosphere/universe/pull/1213

**Comment by OhRobin** [comment]
Installation is find, but `Process data in Scale demo` does not work for me. 

`An error occurred (AccessDenied) when calling the CreateStack operation: User: arn:aws:iam::273854932432:user/roh is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:us-west-2:273854932432:stack/scale-s3-demo/*`

**Comment by gisjedi** [comment]
@OhRobin Thanks for looking at this PR. This sounds like an issue with the user that you are using to run the CreateStack operation not having sufficient privileges to perform the operations outlined in the CloudFormation template. Are you running as an AWS account superuser? I believe this is necessary for this entire section. I can clarify the documents to indicate that requirement. In short, the AWS user must have S3, SQS, SNS and IAM full access.

**Comment by ryadav88** [comment]
@gisjedi The Universe PR is now merged. I've validated the examples. 
Can you still clarify the example to indicate the privileges requirement?

**Comment by gisjedi** [comment]
@ryadev88 I've updated it to just clarify AdministratorAccess role is required on the AWS IAM user as there aren't good default IAM roles that encompass all the needed privileges.  Should be good to go.

**Pull request merged**
