### PR TITLE
new documentation for MSOMS

### PR DESCRIPTION
**Pull request by keikhara**
#17 

Added the documentation for OMS. Please check. 

thanks,

@amitsara
@ryadav88

### CODE REVIEW

**Comment by ryadav88** [comment]
Thanks @keikhara
@mhausenblas ready to review and this resolves https://github.com/dcos/examples/issues/17

**Comment by mhausenblas** [comment]
Thanks for this PR @keikhara! Can I please ask you to do the testing and docs on DC/OS 1.8?

**Comment by mhausenblas** [comment]
Yes please @keikhara … when I put an example together I carry out all the steps (ideally with both CLI and UI instructions and the expected result.

**Comment by keikhara** [comment]
Ok will get do this and let you know.

**Comment by mhausenblas** [comment]
Any updates here @keikhara?

**Comment by keikhara** [comment]
Hi Michael,

Let me work on this and get back to you.

Thanks,

Keiko

**Comment by mhausenblas** [comment]
@ryadav88 can you please let me know where we are with this one?

**Comment by mhausenblas** [comment]
@keikhara @ryadav88 if we don't advance this, maybe close the PR for now until we have everything together?

**Comment by ryadav88** [comment]
@keikhara  This installation doc will be valuable for new users to understand what OMS is and how to run it on DC/OS . let me know if you need any help?

**Comment by keikhara** [comment]
Hi Ravi,

I am back from London. Will work on it asap and will get back to you.

**Comment by keikhara** [comment]
I should get something out by tomorrow. Sorry for the delay since I was out of town for business.

On Dec 4, 2016 12:21 AM, Michael Hausenblas <notifications@github.com> wrote:

@keikhara<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkeikhara&data=02%7C01%7Ckeikhara%40microsoft.com%7Cae990a7d0a1b498947df08d41c1e7d72%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636164364669956704&sdata=b8jDvt%2FS2xu7h6Dx%2B9tuCc1fTklMd4kK%2B3V%2B4blKXUA%3D&reserved=0> @ryadav88<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fryadav88&data=02%7C01%7Ckeikhara%40microsoft.com%7Cae990a7d0a1b498947df08d41c1e7d72%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636164364669956704&sdata=6HzCO0af5eeY7dwR2Si%2Fs%2Ba107mJsMXbBlP9lamkkCI%3D&reserved=0> if we don't advance this, maybe close the PR for now until we have everything together?

**Comment by keikhara** [comment]
Procedure has been tested. They work fine no issue. Also please let me know whether the documentation reads thru smoothly. I did do some clean up. 

Let me add the cli pieces today. We never done this in CLI so we just need to test it.

**Comment by keikhara** [comment]
@mhausenblas Hi Michael, can we add the cli later on once the dev is back? I would like to push what we have and what is working. Let me know thanks.

**Comment by mhausenblas** [comment]
Yes, looks all good to me @keikhara and thanks a lot for this, much appreciated! BTW, looks like I should be covering this, [again](http://tinyletter.com/mhausenblas/letters/appops-reloaded-0) ;)

**Pull request merged**
