### PR TITLE
Bookkeeper example first version.

### PR DESCRIPTION
**Pull request by jiazhai**
Bookkeeper example of first version.

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks a lot for this contrib @jiazhai! Now, seems like `bookkeeper` is not yet in the Universe (from what I can tell from the screen shots you seem to have deployed it in your private, local Universe). So, before we can merge this example (which BTW looks really good) we need to make sure that the  `bookkeeper` package is actually available in the [public Universe](https://github.com/mesosphere/universe). Can you please send in a PR to make it part of the public Universe? If you need help for this, adding my colleague @ryadav88 here.

**Comment by jiazhai** [comment]
Thanks a lot, @mhausenblas. There is already a PR in public Universe under review, and It is in that code-review that @ryadav88's adviced to have this example.
Thanks a lot for your help. I will comments here, once the PR for public universe is done.

**Comment by mhausenblas** [comment]
Thanks a lot for clarifying this @jiazhai and @ryadav88 can you please point me to it, I failed to find the PR?

**Comment by ryadav88** [comment]
@mhausenblas https://github.com/mesosphere/universe/pull/797

**Comment by ryadav88** [comment]
@mhausenblas Universe PR https://github.com/mesosphere/universe/pull/797 is merged. This is ready for review.

**Comment by jiazhai** [comment]
@ryadav88. Thanks so much for your help.

**Comment by mhausenblas** [comment]
Thanks a lot @jiazhai!

**Pull request merged**
