### PR TITLE
Add calico.

### PR DESCRIPTION
**Pull request by djosborne**

### CODE REVIEW

**Comment by mhausenblas** [comment]
Overall LGTM @djosborne thanks! Can I please ask you to add a 1-2 sentence overview on what Calico is as well as Prerequisites section, see for example https://github.com/dcos/examples/tree/master/1.8/linkerd …

**Comment by ryadav88** [comment]
Universe PR is now merged

**Comment by mhausenblas** [comment]
Cool, thanks @ryadav88! @djosborne any ETA for the requested changes?

**Comment by djosborne** [comment]
@mhausenblas done. let me know if that will suffice

**Comment by mhausenblas** [comment]
That is perfect @djosborne thank you so much!!

**Pull request merged**
