### PR TITLE
Add Clair example

### PR DESCRIPTION
**Pull request by tobilg**
This adds the example for the upcoming Clair Universe package. Please don't merge yet.

### CODE REVIEW

**Comment by tobilg** [comment]
cc @ryadav88 Please have a look. Thanks!

**Comment by tobilg** [comment]
Universe PR is good to go. Thanks!

**Comment by ryadav88** [comment]
@tobilg Can you also create a 1.9 directory here and dump the example there (see other examples).

**Comment by tobilg** [comment]
@ryadav88 Done. Please check. Thanks!

**Pull request merged**
