### PR TITLE
Adding ethereum example

### PR DESCRIPTION
**Pull request by drewkerrigan**
Corresponding Universe PR: https://github.com/mesosphere/universe/pull/2097

### CODE REVIEW

**Comment by drewkerrigan** [comment]
@ryadav88 Sure I'll run some tests. How many private agents did you have and how much CPUs / RAM / Disk were available on each?

**Comment by drewkerrigan** [comment]
@ryadav88 Could you please re-run your test and provide the private agent CPUs, RAM, and Disk available?

**Comment by drewkerrigan** [comment]
@vishnu2kmohan It appears that @ryadav88 may not be available to test this, would you have time to help get this and https://github.com/mesosphere/universe/pull/2097 across the finish line with me? I can provide assistance testing anytime.

**Comment by ryadav88** [comment]
@drewkerrigan I was running a 5 node EE permissive cluster w/ 5 private agents with ~ Disk 74.5 GiB, Mem 14.7 GiB, CPUs 4. Looking at your prereqs now, that might be it since each Ethereum node would need alteast 6.1 CPU shares, 6.3GiB of memory and 90GiB of disk

**Pull request merged**
