### PR TITLE
additional linkerd instructions for enterprise

### PR DESCRIPTION
**Pull request by siggy**
depends on https://github.com/mesosphere/universe/pull/855

### CODE REVIEW

**Comment by ryadav88** [comment]
@mhausenblas Universe PR is merged. This is ready to review and merge.

**Comment by ryadav88** [comment]
@mhausenblas ready for review

**Comment by mhausenblas** [comment]
@siggy @ryadav88 LGTM, thanks! One thing though (style guide, consistency): we in general use the prompt in shell interactions, so `$ dcos ...` rather than `dcos ...` – is that something you can fix quickly, otherwise I do it later?

**Comment by siggy** [comment]
@mhausenblas updated to use `$` for shell interactions.
there's one section i did not make this change: https://github.com/dcos/examples/pull/28/files#diff-a023fc8c89a955f59bd2fff80ecb7774R79 ... as it's a multiline heredoc, and thought it might look weird with a `$` on every line. i can change it if you like, just let me know.

**Comment by mhausenblas** [comment]
That's perfect, thanks @siggy!

**Pull request merged**
