### PR TITLE
Add SQL server example

### PR DESCRIPTION
**Pull request by fernandosanchezmunoz**
associated Universe PR: https://github.com/mesosphere/universe/pull/862

based on 

https://blogs.technet.microsoft.com/dataplatforminsider/2016/11/16/announcing-sql-server-on-linux-public-preview-first-preview-of-next-release-of-sql-server/
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup

### CODE REVIEW

**Comment by ryadav88** [comment]
@mhausenblas Universe PR merged. This is ready to review and merge

**Comment by mhausenblas** [comment]
This is awesome, thanks @fernandosanchezmunoz … just one little thing, if I may ask you (to keep things consistent): can you please change all shell interactions to include the prompt, that is `$ command` rather than `command`?

**Comment by ryadav88** [comment]
@mhausenblas can I ask you to add a section called example contribution guidelines to the README where we can add pointers like these? Would be helpful for me. I can point people to it before they starting them. WDYT?

**Comment by mhausenblas** [comment]
@ryadav88 sure.

**Pull request merged**
