### PR TITLE
Update for DCOS 1.9

### PR DESCRIPTION
**Pull request by jsilberm**
Update examples to reflect Portworx on DCOS 1.9

### CODE REVIEW

**Comment by joerg84** [comment]
@jsilberm Am I mistaken or are the screenshots DC/OS 1.8?

**Comment by jsilberm** [comment]
Okay, should be good to go now.  If not, please let me know.

**Comment by joerg84** [comment]
LGTM.

**Comment by joerg84** [comment]
@jsilberm Thanks for your contribution!

**Pull request merged**
